import React, { useState, useEffect, useRef } from 'react';
import { runMAS, getUserRuns } from '../api';
import './UserDashboardSimple.css';

function UserDashboardSimple({ user, onLogout }) {
  const [messages, setMessages] = useState([
    { 
      type: 'assistant', 
      text: '👋 Hi! I\'m your AI coding assistant powered by Multi-Agent System. Just describe what you want to code, and I\'ll generate it for you!',
      timestamp: new Date()
    }
  ]);
  const [inputText, setInputText] = useState('');
  const [loading, setLoading] = useState(false);
  const [expandedMetrics, setExpandedMetrics] = useState({});
  const [recentRuns, setRecentRuns] = useState([]);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [currentConversationId, setCurrentConversationId] = useState(null);
  const [showHistoryDropdown, setShowHistoryDropdown] = useState(false);
  const messagesEndRef = useRef(null);
  const dropdownRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
        setShowHistoryDropdown(false);
      }
    };

    if (showHistoryDropdown) {
      document.addEventListener('mousedown', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [showHistoryDropdown]);

  useEffect(() => {
    loadRecentRuns();
  }, []);

  const loadRecentRuns = async () => {
    try {
      const runs = await getUserRuns();
      setRecentRuns(runs);
    } catch (error) {
      console.error('Failed to load recent runs:', error);
    }
  };

  const startNewChat = () => {
    setMessages([
      { 
        type: 'assistant', 
        text: '👋 Hi! I\'m your AI coding assistant. What would you like to code today?',
        timestamp: new Date()
      }
    ]);
    setCurrentConversationId(null);
    setExpandedMetrics({});
  };

  const loadConversation = (run) => {
    setMessages([
      { 
        type: 'assistant', 
        text: '📂 Previous conversation loaded.',
        timestamp: new Date(run.created_at)
      },
      {
        type: 'user',
        text: run.task,
        timestamp: new Date(run.created_at)
      },
      {
        type: 'assistant',
        text: '✅ Here\'s your code:',
        code: run.code,
        metrics: {
          predicted_score: run.predicted_score,
          features: run.features,
          run_id: run._id
        },
        timestamp: new Date(run.created_at)
      }
    ]);
    setCurrentConversationId(run._id);
    setSidebarOpen(false); // Close sidebar on mobile
  };

  const handleSendMessage = async () => {
    if (!inputText.trim() || loading) return;

    const userMessage = inputText.trim();
    setInputText('');

    // Add user message
    const userMsg = {
      type: 'user',
      text: userMessage,
      timestamp: new Date()
    };
    setMessages(prev => [...prev, userMsg]);
    setLoading(true);

    try {
      // Call MAS API
      const response = await runMAS(userMessage, '');
      
      // Add assistant response with code and metrics
      const assistantMsg = {
        type: 'assistant',
        text: '✅ Code Generated by Multi-Agent System:',
        initial_code: response.initial_code || response.code,
        final_code: response.final_code || response.code,
        metrics: {
          initial_score: response.initial_score || response.predicted_score,
          final_score: response.predicted_score,
          enhancement_loops: response.enhancement_loops || 0,
          auto_enhanced: response.auto_enhanced,
          features: response.features,
          run_id: response.run_id
        },
        timestamp: new Date()
      };
      
      setMessages(prev => [...prev, assistantMsg]);
      
      // Reload recent runs to include this new one
      loadRecentRuns();
      
    } catch (error) {
      // Add error message
      const errorMsg = {
        type: 'assistant',
        text: `❌ Sorry, something went wrong: ${error.message}`,
        isError: true,
        timestamp: new Date()
      };
      setMessages(prev => [...prev, errorMsg]);
    } finally {
      setLoading(false);
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const toggleMetrics = (index) => {
    setExpandedMetrics(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  return (
    <div className="simple-dashboard">
      {/* Top Navigation Bar */}
      <div className="history-menubar">
        <button 
          className="sidebar-toggle-button"
          onClick={() => setShowHistoryDropdown(!showHistoryDropdown)}
          title="Toggle sidebar"
        >
          <span className="menu-icon">☰</span>
        </button>
        
        <div className="menubar-title">
          AgentMonitor - Multi-Agent Code Assistant
        </div>
        
        <div className="user-info">
          <span className="username">👤 {user.username}</span>
          <button className="logout-button-top" onClick={onLogout}>
            Logout
          </button>
        </div>
      </div>

      {/* Dashboard Content Area (Below Navbar) */}
      <div className="dashboard-content">
        {/* ChatGPT-Style Sidebar */}
        {showHistoryDropdown && (
          <>
            <div 
              className="sidebar-overlay" 
              onClick={() => setShowHistoryDropdown(false)}
            ></div>
            <div className="chat-sidebar" ref={dropdownRef}>
              <div className="sidebar-header">
                <button 
                  className="new-chat-btn"
                  onClick={() => {
                    startNewChat();
                    setShowHistoryDropdown(false);
                  }}
                >
                  <span className="btn-icon">+</span>
                  <span>New Chat</span>
                </button>
              </div>
              
              <div className="sidebar-content">
                <h3 className="sidebar-title">Recent Conversations</h3>
                <div className="recent-list">
                  {recentRuns.length === 0 ? (
                    <div className="empty-state">
                      <span style={{color: '#999', fontSize: '0.9rem'}}>No previous conversations</span>
                    </div>
                  ) : (
                    recentRuns.map((run, idx) => (
                      <div 
                        key={run._id || idx}
                        className={`chat-item ${currentConversationId === run._id ? 'active' : ''}`}
                        onClick={() => {
                          loadConversation(run);
                          setShowHistoryDropdown(false);
                        }}
                        title={run.task}
                      >
                        <span className="chat-icon">💬</span>
                        <div className="chat-info">
                          <div className="chat-title">
                            {run.task?.substring(0, 45) || 'Untitled'}
                            {run.task?.length > 45 && '...'}
                          </div>
                          <div className="chat-meta">
                            <span className="chat-score">⭐ {run.predicted_score?.toFixed(2) || 'N/A'}</span>
                          </div>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>
            </div>
          </>
        )}

        {/* Main Chat Area */}
        <div className="main-chat-area">
          {/* Chat Container */}
          <div className="chat-container">
        {/* Messages */}
        <div className="messages-area">
          {messages.map((msg, index) => (
            <div key={index} className={`message-wrapper ${msg.type}`}>
              <div className="message-bubble">
                {/* Message Text */}
                <div className="message-text">{msg.text}</div>

                {/* Code Comparison (Initial vs Final) */}
                {(msg.initial_code || msg.final_code) && (
                  <div className="code-comparison-block">
                    <div className="comparison-header">
                      <h4>🤖 Multi-Agent Code Generation</h4>
                      {msg.metrics && (
                        <div className="score-comparison">
                          <span className="score-badge initial">
                            Initial: {msg.metrics.initial_score?.toFixed(3) || 'N/A'}
                          </span>
                          <span className="arrow">→</span>
                          <span className="score-badge final">
                            Final: {msg.metrics.final_score?.toFixed(3) || 'N/A'}
                          </span>
                          {msg.metrics.enhancement_loops > 0 && (
                            <span className="enhancement-badge">
                              ✨ Enhanced {msg.metrics.enhancement_loops}x
                            </span>
                          )}
                        </div>
                      )}
                    </div>

                    <div className="code-comparison-panels">
                      <div className="code-panel">
                        <div className="panel-label">📝 Initial Code</div>
                        <pre className="code-content">{msg.initial_code || 'N/A'}</pre>
                      </div>
                      
                      <div className="comparison-divider">→</div>
                      
                      <div className="code-panel">
                        <div className="panel-label">✨ Final Code</div>
                        <pre className="code-content highlighted">{msg.final_code || msg.initial_code || 'N/A'}</pre>
                      </div>
                    </div>
                    
                    {/* Metrics Toggle */}
                    {msg.metrics && (
                      <button 
                        className="metrics-toggle"
                        onClick={() => toggleMetrics(index)}
                      >
                        {expandedMetrics[index] ? '📊 Hide MAS Metrics' : '📊 Show MAS Metrics'}
                      </button>
                    )}
                  </div>
                )}

                {/* Collapsible Metrics Panel */}
                {msg.metrics && expandedMetrics[index] && (
                  <div className="metrics-panel">
                    <h4>� Multi-Agent System Metrics</h4>
                    
                    <div className="metrics-section">
                      <h5>🎯 MAS Scores (XGBoost Predicted)</h5>
                      <div className="metrics-grid">
                        <div className="metric-item">
                          <div className="metric-label">Initial MAS Score</div>
                          <div className="metric-value">
                            {msg.metrics.initial_score?.toFixed(4) || 'N/A'}
                          </div>
                        </div>
                        
                        <div className="metric-item">
                          <div className="metric-label">Final MAS Score</div>
                          <div className="metric-value highlight">
                            {msg.metrics.final_score?.toFixed(4) || 'N/A'}
                          </div>
                        </div>
                        
                        <div className="metric-item">
                          <div className="metric-label">Score Improvement</div>
                          <div className="metric-value success">
                            +{((msg.metrics.final_score - msg.metrics.initial_score) * 100).toFixed(1)}%
                          </div>
                        </div>
                        
                        <div className="metric-item">
                          <div className="metric-label">Enhancement Loops</div>
                          <div className="metric-value">
                            {msg.metrics.enhancement_loops || 0}
                          </div>
                        </div>
                      </div>
                    </div>
                    
                    <div className="metrics-section">
                      <h5>👥 Agent Collaboration</h5>
                      <div className="metrics-grid">
                        <div className="metric-item">
                          <div className="metric-label">Agents Used</div>
                          <div className="metric-value">
                            {msg.metrics.features?.num_nodes || 4}
                          </div>
                        </div>
                        
                        <div className="metric-item">
                          <div className="metric-label">Agent Interactions</div>
                          <div className="metric-value">
                            {msg.metrics.features?.num_edges || 0}
                          </div>
                        </div>
                        
                        <div className="metric-item">
                          <div className="metric-label">Avg Personal Score</div>
                          <div className="metric-value">
                            {msg.metrics.features?.avg_personal_score?.toFixed(4) || 'N/A'}
                          </div>
                        </div>
                        
                        <div className="metric-item">
                          <div className="metric-label">Min Personal Score</div>
                          <div className="metric-value">
                            {msg.metrics.features?.min_personal_score?.toFixed(4) || 'N/A'}
                          </div>
                        </div>
                      </div>
                    </div>
                    
                    <div className="metrics-section">
                      <h5>⚡ Performance</h5>
                      <div className="metrics-grid">
                        <div className="metric-item">
                          <div className="metric-label">Total Latency</div>
                          <div className="metric-value">
                            {msg.metrics.features?.total_latency?.toFixed(2) || '0'}s
                          </div>
                        </div>
                        
                        <div className="metric-item">
                          <div className="metric-label">Token Usage</div>
                          <div className="metric-value">
                            {msg.metrics.features?.total_token_usage || 0}
                          </div>
                        </div>
                      </div>
                    </div>
                    
                    {msg.metrics.auto_enhanced && (
                      <div className="enhancement-notice">
                        ✨ This code was automatically enhanced by the Multi-Agent System to improve quality
                      </div>
                    )}
                  </div>
                )}

                {/* Timestamp */}
                <div className="message-time">
                  {msg.timestamp.toLocaleTimeString()}
                </div>
              </div>
            </div>
          ))}
          
          {/* Loading Indicator */}
          {loading && (
            <div className="message-wrapper assistant">
              <div className="message-bubble">
                <div className="loading-indicator">
                  <div className="dot"></div>
                  <div className="dot"></div>
                  <div className="dot"></div>
                  <span>Generating code...</span>
                </div>
              </div>
            </div>
          )}
          
          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="input-area">
          <textarea
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder="Describe what you want to code... (e.g., 'Create a function to sort an array')"
            disabled={loading}
            rows="3"
          />
          <button 
            onClick={handleSendMessage}
            disabled={loading || !inputText.trim()}
            className="send-button"
          >
            {loading ? '⏳' : '🚀 Generate'}
          </button>
        </div>
      </div>
      </div>
    </div>
    </div>
  );
}

export default UserDashboardSimple;
